### ISSUE TITLE
サーバ側着工する

### ISSUE THREAD

**Issue by vvakame** [mercari/mtc2018-web#1]
いい加減やりはじめましょ。

* Microserviceっぽくするやつ？
  * gRPCどうする？
* GraphQL
  * やっていき 💪 

思いついた仕様は適宜書き留めていく。
誰でもdescription編集していいし、コメントに書いてもよいです。

**Comment by vvakame** [comment]
なお、利用言語は議論の余地なくGoです！(誰もGo以外を使う発想が無さそう

**Comment by kazegusuri** [comment]
モノリシックな場合ってgRPCかGraphQLかって混ぜられないですよね。どちらを使うかはどちらでも大丈夫です。GraphQLわからないのでGraphQLやってみるでいいかも

**Comment by Code-Hex** [comment]
利用言語は Perl です！（嘘です）

**Comment by vvakame** [comment]
とりあえずSNSログイン(Google)いるよね という話があったので雑にやるぞ

**Comment by vvakame** [comment]
とっくに手をつけてた…
このIssue役に立ってないので閉じます
