### ISSUE TITLE
`web/` 配下についてのご相談

### ISSUE THREAD

**Issue by sawa-zen** [mercari/mtc2018-web#6]
@adwd nakayama先生がLPの仮ワイヤーをあげてくれたのでLPの仮マークアップをやっていこうと思っています :+1:  それで一点だけご相談なんですが 基本的には `src/` 配下に作業ファイルを置きたいと思っとりますです。理由は↓こんな感じ

```
- `pages/` 配下にファイルを置くとpageとしてみなされてしまう
- ディレクトリルートが散らかる
```

なので基本的には `pages/` のファイルは処理を書かずに、 `containers/` 配下のファイルを `import` して即 `export` する形式にしたいっす

```
import Top from '../src/containers/Top';
export default Top;
```

なのでなので `components/` ディレクトリはなるべく Moleculesレベル (コンテキストを含まないレベル) のcomponentを配置して コンテキストを含むcomponentは `containers/` 配下に置こうと思います。

↓こんな感じ
```
- pages/ ← ただページを存在させるためだけのファイル群
  - top.ts
  - sub.ts
- src/
  - components/ ← コンテキストを含まない群 (UIパッケージとして切り出せちゃうレベル)
    - index.ts
    - Button.tsx
    - Card.tsx
    - TextField.tsx
    - etc...
  - containers/ ← コンテキストを含む群
    - Top/ 
      - index.tsx
      - HeaderNav.tsx
    - Sub/
      - index.tsx
    - etc...
```

next.jsの公式のexampleとかとは少し違いますが、よければこの構成で進めて行きたく存じます 🙇

**Comment by adwd** [comment]
components/containersは必要そうですね。
でもsrcって言われるとその下にソースコードがあると思うしpagesが浮いてるように思えるんですよね。pagesにgetInitialPropsとかのロジックは入ってくると思いますし。
pages/components/containersみたいにフォルダが並んでるのはどうですかね？

**Comment by sawa-zen** [comment]
next.jsだけじゃなくnuxtも同じ問題があるんですが `pages/` 以下をpageとみなしてくれる機能は便利な反面ディレクトリを扱いずらくしてしまっているんですよね 🤔 
ルートにはconfig系やlint系が乱立するのでそこと同じ階層に `components` とかが置かれることに個人的に違和感がありやす。

**Comment by adwd** [comment]
Bパターンです！
pagesにはNext.js特有の_app,_documentとかgetInitialPropsとかルーティングのロジックを書くべきだと思ってます。
ルートにpagesがある以上componentsが来てもいいと思いますし、lint系とかをconfigsにまとめておくとかでもいいのでは。

srcありでもいい気がしてきましたが
```
import Top from '../src/containers/Top';
export default Top;
```
はいらなくないですか？pagesで `import Top from '../src/containers/Top' ってすればいいので。

**Comment by sawa-zen** [comment]
なるほどぉ。ルーティングとしての責務はpages配下でちゃんと行って、本来のコンテナとしての機能からはじめてcontainer配下に書く。それでも良さそう。じゃあ一旦srcで着るのやめててっぺんに置きます :ok_woman:

**Comment by adwd** [comment]
いったんそれでいいですかね 🙇 
あとで散らかってきたらsrcに移動したくなるかも 😇
